### PR TITLE
Validate deployment config file

### PR DESCRIPTION
**Pull request by adrianmo**
Validate the deployment yaml file with a schema before starting with the deployment process.

### CODE REVIEW

**Comment by adrianmo** [comment]
I've tested it and it's working fine, but I still need to refactor the schema file to reduce duplicated code and beautify the validation error output.

**Comment by padthaitofuhot** [comment]
Does this wholly or partially implement #204 ?

**Comment by adrianmo** [comment]
It wholly implements it. But it's still in progress as I need to implement what I mentioned in the previous comment.

**Comment by adrianmo** [comment]
@padthaitofuhot yes, you can already review it and give me some feedback.

I can't use partial schemas to remove duplicated code yet as the latest release of the pykwalify library broke them and the previous one is not working fine with extensions...

We need to keep track of this issue: https://github.com/Grokzen/pykwalify/iss ues/88

Please don't merge it yet as I will rebase it and squash it before the merge.

**Comment by padthaitofuhot** [comment]
Yes and heard to everything you said.  
Have you considered a pykwalify alternative?  I'm partial to Yamale, but I haven't done much research on YAML schema validators.

- Yamale https://github.com/23andMe/Yamale
- Voluptuous https://github.com/alecthomas/voluptuous

I've added this to the next milestone in the hopes it'll be complete by then.

**Comment by adrianmo** [comment]
@padthaitofuhot actually, this is already complete. The validation is working fine and it's integrated into the step1 deployment. It can be merged already and I'll keep track of the issue and update the schema once the original library gets the bug fixed.

**Comment by adrianmo** [comment]
@padthaitofuhot I took a look at the alternatives you suggested. Yamale is the one that can be a good alternative, so I tested it and it works fine with the partial schemas and "includes", but there is no "strict" mode to check for keys that are not in the schema. That means that if you have a typo in an optional key, it will be ignored by Yamale and will validate it. There is an open issue reporting this feature for more than one year but still not implemented (https://github.com/23andMe/Yamale/iss ues/27).

So, IMO our best option is continue using pykwalify, which validates correctly in strict mode, and refactor the schema when the partial schemas are fixed.

**Comment by padthaitofuhot** [comment]
@adrianmo Woot.  I'll review it.

**Comment by padthaitofuhot** [comment]
@adrianmo Do we have a set of tests for this?

**Comment by padthaitofuhot** [comment]
Also, I'm impressed with how deftly you worked around my n00b pythoning, especially that Director class. 💃 Anyway, this looks good.  There's two more commits before we merge it:

```
The deployment file at '/opt/deploy.yml' is not valid.
```
1. The path given here should follow the outer (host) path, not the inner (container) path.  The droid you are looking for is `host_root` from `defaults.py`. 
```
Schema validation failed:
 - Cannot find required key 'ecs_software_image'. Path: '/facts'.
```
2. ecs_software_image was removed from deploy.yml.  Its behavior was migrated full into release.conf.

That should be it.  Let's get this merged!

**Comment by adrianmo** [comment]
@padthaitofuhot Thanks for the review. I have just pushed a couple of commits fixing the issues you mentioned. Let me know how it looks.

About the testing, as we don't do any testing yet, I think we should talk about a global testing strategy for the project and work on that on a separate thread.

**Comment by padthaitofuhot** [comment]
Opened #217 to discuss global testing strategy.  I'll review this one more time today with the new commits and probably merge it.

**Comment by adrianmo** [comment]
Sounds good.

**Comment by padthaitofuhot** [comment]
Merged.

**Pull request merged**
