### PR TITLE
[WiP] Update ecs-install Python requirements

### PR DESCRIPTION
**Pull request by padthaitofuhot**

### CODE REVIEW

**Comment by padthaitofuhot** [comment]
```
TASK [install_node : Run Step1] ************************************************
fatal: [10.1.83.104]: FAILED! => {"changed": true, "cmd": "step1", "delta": "0:00:05.322273", "end": "2017-09-21 11:58:16.832696", "failed": true, "rc": 1, "start": "2017-09-21 11:58:11.510423", "stderr": "Traceback (most recent call last):\n  File \"/usr/local/bin/ecsdeploy\", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3138, in <module>\n    @_call_aside\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3122, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3151, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 666, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 679, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 867, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The 'six==1.10.0' distribution was not found and is required by python-ecsclient\nTraceback (most recent call last):\n  File \"/usr/local/bin/ecsdeploy\", line 6, in <module>\n    from pkg_resources import load_entry_point\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3138, in <module>\n    @_call_aside\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3122, in _call_aside\n    f(*args, **kwargs)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 3151, in _initialize_master_working_set\n    working_set = WorkingSet._build_master()\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 666, in _build_master\n    return cls._build_from_requirements(__requires__)\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 679, in _build_from_requirements\n    dists = ws.resolve(reqs, Environment())\n  File \"/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py\", line 867, in resolve\n    raise DistributionNotFound(req, requirers)\npkg_resources.DistributionNotFound: The 'six==1.10.0' distribution was not found and is required by python-ecsclient", "stdout": "ecs-install> Initializing data container, one moment ... OK\necs-install> Applying deploy.yml\n> ", "stdout_lines": ["ecs-install> Initializing data container, one moment ... OK", "ecs-install> Applying deploy.yml", "> "], "warnings": []}
```

**Comment by padthaitofuhot** [comment]
@adrianmo related to https://github.com/EMCECS/python-ecsclient/pull/44

**Comment by adrianmo** [comment]
@padthaitofuhot I want to include the VDC Keystore feature (https://github.com/EMCECS/python-ecsclient/pull/41) in the 1.1.5 milestone (https://github.com/EMCECS/python-ecsclient/milestone/4), which will include the dependencies update. Can you please take a look at the PR so I can get it merged and release v1.1.5?

Thanks!

**Comment by padthaitofuhot** [comment]
@adrianmo Reviewed.  Cheers.

**Pull request merged**
