### PR TITLE
[WIP] Creates RTD with Bootstrap and Dell Bootstrap theme.

### PR DESCRIPTION
**Pull request by captntuttle**
Initial PR addressing #227

Up to date RTD page: http://ecs-community-edition.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by padthaitofuhot** [comment]
- "Source" link links to the RST file in the actual github repo so users can submit PRs really easy.
- README.md?  What's the relationship between MD and RST files in main repo docs like README, license, changelog, etc?
-  Check bulleted list conversion from MD, for example: https://github.com/captntuttle/ECS-CommunityEdition/blob/ECS-CommunityEdition-227/docs/source/use/ECS-UI-Automation.rst
- Need docs for new installer

**Comment by padthaitofuhot** [comment]
I agree with a lot of what @adrianmo is saying, but I know he and I are both pleased as punch to have *any documentation at all* at this point, so please take our criticisms like a salty caramel.  I would seriously implementing some of Adrian's UX comments, however, because the easier it is for consumers to find the information they're looking for, the more time will be available for us to work on the project rather than docbug-generated support issues.  Generally, though: 👍

**Comment by adrianmo** [comment]
Right, it's a huge step forward compared to what we had until now. The UI/UX notes I said is something we can deal after we merge this PR and have an initial version released.

**Comment by captntuttle** [comment]
* source goes to GitHub report
* Install docs (rough or otherwise) written

**Comment by padthaitofuhot** [comment]
@captntuttle So, where are we at with this?  Is it ready enough that if we merge it into develop and cut a release it'll be OK?

**Comment by captntuttle** [comment]
@padthaitofuhot Yes, I believe so. I'm working on cosmetics/organization right now, but that and additional documentation can follow the release.

**Comment by padthaitofuhot** [comment]
Fantastic.  Can you prioritize building the new README file for the repo root?  We can probably cut a release if we have that done and I get this last requirement PR merged.

**Comment by captntuttle** [comment]
Working on the readme now.

**Comment by captntuttle** [comment]
Okay, readme and license display on the index file.

**Pull request merged**
