### PR TITLE
documentation-build-tools

### PR DESCRIPTION
**Pull request by captntuttle**
### This pull request addresses the following referenced issue(s):

1. #385
2.
3.

### Overview of changes:

1. Adds docker file for translating from .md to .rst
2.
3.

---
@padthaitofuhot @captntuttle @adrianmo

### CODE REVIEW

**Comment by padthaitofuhot** [comment]
Is there a script to auto-discover .md files, build the documentation, and update RTD?

**Comment by padthaitofuhot** [comment]
@captntuttle ping

**Comment by captntuttle** [comment]
Lost track of this.

RTD will update auto-magically when new documentation is merged but this is missing the script to find changed .md files and convert them to .rst.

I have the script written somewhere, I'll figure out what happened to it and why it got left out.

**Comment by captntuttle** [comment]
I scrapped the whole thing and re-did this a better way. Killing this PR and pushing a new one.

**Pull request closed without merging**
